#!/bin/sh

# BRANCH NAMING POLICY
GIT_FLOW_REGEX="(^feature\/)|(^bugfix\/)|(^hotfix\/)"
JIRA_BRANCH_NAME_REGEX="($GIT_FLOW_REGEX)(([A-Z]{4}-[0-9]{4}|merge))"

# ERROR MESSAGES
ERROR_BRANCH_NAME="feature, bugfix or hotfix is missing from the branch name."
ERROR_JIRA_BRANCH_NAME="Jira ticket number is missing from the branch name."

current_branch="$(git rev-parse --abbrev-ref HEAD)"
error=""

if [[ ! $current_branch =~ $GIT_FLOW_REGEX ]]
then
    echo "$ERROR_BRANCH_NAME"
    exit 1
fi

if [[ ! $current_branch =~ $JIRA_BRANCH_NAME_REGEX ]]
then
    echo "$ERROR_JIRA_BRANCH_NAME"
    exit 1
fi
